### PR TITLE
Fix oxum calculation

### PR DESCRIPTION
**Pull request by henning-gerhardt**
A simple solution for correction #1

### CODE REVIEW

**Comment by whikloj** [comment]
Hey @henning-gerhardt.

Good catch and thanks for this. Would you be willing to write a test to capture this issue so I don't make this mistake again?

**Comment by henning-gerhardt** [comment]
I can try it. I would extend the `ExtendedBagTest` class for this, if this is correct place.

**Comment by whikloj** [comment]
Whatever works, I had a plan for the organization of tests but it kinda fell apart so I'm just putting tests where ever seems most appropriate.

**Comment by whikloj** [comment]
Thank you @henning-gerhardt, I'll tag a `1.2.1` version for packagist.

**Pull request merged**
