### PR TITLE
Ensure we start working with an absolute path

### LINKED ISSUE #26: Creation of bag with relative bag fails unless ./ prefix is used
The following code fails:
```
$bag = Bag::create('my_bag_path');
```
...with...
```
PHP Fatal error:  Uncaught whikloj\BagItTools\Exceptions\FilesystemException: Unable to put contents to file /my_bag_path/bagit.txt in /.../vendor/whikloj/bagittools/src/BagUtils.php:283
```
It appears that `my_bag_path` is interpreted as an absolute path unless you prefix it with `./`

I'm not sure if this is intentional, but in my opinion this library should behave like the PHP file functions, which would interpret `my_bag_path` as a relative path unless there is a `/` prefix in front.

### PR DESCRIPTION
**Pull request by whikloj**
Resolves #26

### CODE REVIEW

**Comment by whikloj** [comment]
@asmecher do you want to give this a try? I apologize that this simple change has come at the cost of removing PHP 7.2 support. I'll cut this as a `^3.0` release

**Comment by whikloj** [comment]
@asmecher I updated main to remove PHP 7.2 support and fix all the other underlying bits. So now this PR is just about the issue at hand. Please have a look and let me know if I am meeting the use-case.

**Comment by asmecher** [comment]
Thanks, @whikloj! I tested this by applying https://github.com/whikloj/BagItTools/pull/27.diff to my Composer-based installation (version 2.1.0). The patch applied successfully (with a bit of noise due to upstream changes):
```
patching file src/Bag.php
Hunk #3 succeeded at 523 with fuzz 2.
Hunk #4 succeeded at 1176 (offset 2 lines).
patching file src/BagUtils.php
Hunk #2 succeeded at 125 with fuzz 2.
Hunk #3 succeeded at 140 (offset 1 line).
patching file tests/BagInternalTest.php
patching file tests/BagTest.php
Hunk #1 succeeded at 18 with fuzz 1 (offset -1 lines).
Hunk #2 succeeded at 30 (offset -1 lines).
Hunk #3 succeeded at 94 (offset -1 lines).
Hunk #4 succeeded at 774 (offset -11 lines).
Hunk #5 succeeded at 968 (offset -19 lines).
patching file tests/BagUtilsTest.php
Hunk #1 succeeded at 75 (offset -1 lines).
```
I tested this with a relative path and it worked fine where it previously failed.

Recent releases of our software require PHP7.3, so the PHP7.2 loss isn't a problem.

Thanks for the quick turn-around on this, I appreciate it!

**Comment by whikloj** [comment]
I'll tag a 3.0.1 in the morning

**Comment by asmecher** [comment]
Thanks, @whikloj, much appreciated!

**Pull request merged**
